insert into Playlist (ID, URL, name, IDuser) values (1, 'www.bdadTube.com/playlist1', 'in quis justo maecenas rhoncus aliquam', 49);
insert into Playlist (ID, URL, name, IDuser) values (2, 'www.bdadTube.com/playlist2', 'pede justo lacinia eget tincidunt eget', 16);
insert into Playlist (ID, URL, name, IDuser) values (3, 'www.bdadTube.com/playlist3', 'morbi a ipsum', 7);
insert into Playlist (ID, URL, name, IDuser) values (4, 'www.bdadTube.com/playlist4', 'non mauris morbi non lectus aliquam', 45);
insert into Playlist (ID, URL, name, IDuser) values (5, 'www.bdadTube.com/playlist5', 'et magnis dis parturient montes nascetur', 41);
insert into Playlist (ID, URL, name, IDuser) values (6, 'www.bdadTube.com/playlist6', 'id nisl venenatis', 14);
insert into Playlist (ID, URL, name, IDuser) values (7, 'www.bdadTube.com/playlist7', 'iaculis diam erat fermentum justo nec', 45);
insert into Playlist (ID, URL, name, IDuser) values (8, 'www.bdadTube.com/playlist8', 'amet lobortis sapien', 29);
insert into Playlist (ID, URL, name, IDuser) values (9, 'www.bdadTube.com/playlist9', 'aliquam augue', 39);
insert into Playlist (ID, URL, name, IDuser) values (10, 'www.bdadTube.com/playlist10', 'leo odio condimentum id luctus nec', 44);
insert into Playlist (ID, URL, name, IDuser) values (11, 'www.bdadTube.com/playlist11', 'velit nec nisi', 12);
insert into Playlist (ID, URL, name, IDuser) values (12, 'www.bdadTube.com/playlist12', 'volutpat dui maecenas tristique', 34);
insert into Playlist (ID, URL, name, IDuser) values (13, 'www.bdadTube.com/playlist13', 'consequat lectus in', 3);
insert into Playlist (ID, URL, name, IDuser) values (14, 'www.bdadTube.com/playlist14', 'amet justo morbi', 10);
insert into Playlist (ID, URL, name, IDuser) values (15, 'www.bdadTube.com/playlist15', 'dui proin leo odio porttitor', 5);
insert into Playlist (ID, URL, name, IDuser) values (16, 'www.bdadTube.com/playlist16', 'tincidunt lacus at', 42);
