insert into PromotingEntity (ID, name) values (1, 'condimentum curabitur');
insert into PromotingEntity (ID, name) values (2, 'dui nec');
insert into PromotingEntity (ID, name) values (3, 'cras mi pede');
insert into PromotingEntity (ID, name) values (4, 'ipsum');
insert into PromotingEntity (ID, name) values (5, 'pulvinar');
insert into PromotingEntity (ID, name) values (6, 'consequat dui');
insert into PromotingEntity (ID, name) values (7, 'ante vestibulum');
insert into PromotingEntity (ID, name) values (8, 'turpis sed');
insert into PromotingEntity (ID, name) values (9, 'in magna bibendum');
insert into PromotingEntity (ID, name) values (10, 'sapien cursus');
insert into PromotingEntity (ID, name) values (11, 'dui');
insert into PromotingEntity (ID, name) values (12, 'dolor sit amet');
insert into PromotingEntity (ID, name) values (13, 'pretium nisl ut');
insert into PromotingEntity (ID, name) values (14, 'sed lacus morbi');
insert into PromotingEntity (ID, name) values (15, 'mattis pulvinar nulla');
insert into PromotingEntity (ID, name) values (16, 'volutpat eleifend donec');
insert into PromotingEntity (ID, name) values (17, 'etiam');
insert into PromotingEntity (ID, name) values (18, 'ac');
insert into PromotingEntity (ID, name) values (19, 'nibh');
insert into PromotingEntity (ID, name) values (20, 'vel augue vestibulum');
insert into PromotingEntity (ID, name) values (21, 'non lectus aliquam');
insert into PromotingEntity (ID, name) values (22, 'condimentum');
insert into PromotingEntity (ID, name) values (23, 'in leo');
insert into PromotingEntity (ID, name) values (24, 'nulla');
insert into PromotingEntity (ID, name) values (25, 'id');
insert into PromotingEntity (ID, name) values (26, 'est');
insert into PromotingEntity (ID, name) values (27, 'turpis donec');
insert into PromotingEntity (ID, name) values (28, 'eu');
insert into PromotingEntity (ID, name) values (29, 'proin interdum');
insert into PromotingEntity (ID, name) values (30, 'sapien quis');
